# CodeAlpha Data Analytics Internship

## Task 1: AI Job Impact Analysis – Exploratory Data Analysis (EDA)

**Intern Name:** Saniya Sheikh

**Domain:** Data Analytics

**Tool Used:** Google Colab (Python)

### Objective

The objective of this project is to prepare the AI Job Impact dataset for data analysis. The dataset is inspected, cleaned, transformed, and enriched with new analytical features so that it becomes suitable for exploratory data analysis and visualization.

### Dataset Description

The dataset contains employee information related to age, gender, education level, industry, job role, AI adoption level, automation risk, salary before AI, salary after AI, job status, work hours, remote work, job satisfaction, and productivity change.

This project includes:

* Data loading
* Data inspection
* Missing value analysis
* Duplicate removal
* Text cleaning
* Feature engineering
* Exporting the cleaned dataset

#  IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option('display.max_columns', None)

# Display width
pd.set_option('display.width', 1000)

# Chart style
sns.set_style('whitegrid')

# Default chart size
plt.rcParams['figure.figsize'] = (10,6)

print('='*60)
print('AI JOB IMPACT ANALYSIS')
print('DATA COLLECTION AND PREPARATION')
print('='*60)
print('Libraries imported successfully')

============================================================
AI JOB IMPACT ANALYSIS
DATA COLLECTION AND PREPARATION
============================================================
Libraries imported successfully

#Load the dataset

In this step, the AI Job Impact dataset is uploaded and loaded into a Pandas DataFrame. The first five records are displayed to verify that the dataset has been imported successfully.

In [3]:
df = pd.read_csv('/content/ai_job_impact.csv')
df.head()

  Employee_ID  Age  Gender Education_Level       Industry           Job_Role  Years_Experience AI_Adoption_Level Automation_Risk Upskilling_Required  Salary_Before_AI  Salary_After_AI Job_Status  Work_Hours_Per_Week Remote_Work  Job_Satisfaction  Productivity_Change_%
0       E0001   50  Female        Bachelor      Marketing    Content Creator                26              High            High                 Yes            106820            95455   Replaced                   45          No                 5                 -10.64
1       E0002   45    Male     High School  Manufacturing  Quality Inspector                19               Low             Low                 Yes             74131            72013  Unchanged                   36         Yes                 6                  19.05
2       E0003   51  Female          Master             IT    DevOps Engineer                28            Medium          Medium                 Yes             35311            42290   Modified                   46         Yes                 3                  17.05
3       E0004   48    Male             PhD      Education            Teacher                24            Medium          Medium                 Yes            114478           107820   Modified                   50          No                 9                  -2.47
4       E0005   24    Male        Bachelor     Healthcare             Doctor                 0              High          Medium                  No             33890            40945   Modified                   52         Yes                 6                   7.03

# Dataset overview

This step examines the dimensions of the dataset and the names of all available variables. Understanding the number of rows and columns is important before performing data cleaning and analysis.

In [4]:
print('Rows and Columns:', df.shape)

print('\nTotal Rows:', df.shape[0])

print('Total Columns:', df.shape[1])

print('\nColumn Names')

for i, col in enumerate(df.columns, start=1):
    print(f'{i}. {col}')

Rows and Columns: (2000, 17)

Total Rows: 2000
Total Columns: 17

Column Names
1. Employee_ID
2. Age
3. Gender
4. Education_Level
5. Industry
6. Job_Role
7. Years_Experience
8. AI_Adoption_Level
9. Automation_Risk
10. Upskilling_Required
11. Salary_Before_AI
12. Salary_After_AI
13. Job_Status
14. Work_Hours_Per_Week
15. Remote_Work
16. Job_Satisfaction
17. Productivity_Change_%

# Basic information

The structure of the dataset is examined using the info() function. This includes data types, total records, and non-null values for each column.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            2000 non-null   object
 1   Age                    2000 non-null   int64
 2   Gender                 2000 non-null   object
 3   Education_Level        2000 non-null   object
 4   Industry               2000 non-null   object
 5   Job_Role               2000 non-null   object
 6   Years_Experience       2000 non-null   int64
 7   AI_Adoption_Level      2000 non-null   object
 8   Automation_Risk        2000 non-null   object
 9   Upskilling_Required    2000 non-null   object
 10  Salary_Before_AI       2000 non-null   int64
 11  Salary_After_AI        2000 non-null   int64
 12  Job_Status             2000 non-null   object
 13  Work_Hours_Per_Week    2000 non-null   int64
 14  Remote_Work            2000 non-null   object
 15  Job_Satisfaction       2000 non-null   int64
 16  Productivity_Change_%  2000 non-null   float64
dtypes: float64(1), int64(6), object(10)
memory usage: 265.8+ KB

# Check missing values

This step checks whether any values are missing in the dataset.

In [6]:
missing_values = df.isnull().sum()

print(missing_values)

print('\nTotal Missing Values:', missing_values.sum())

Employee_ID              0
Age                      0
Gender                   0
Education_Level          0
Industry                 0
Job_Role                 0
Years_Experience         0
AI_Adoption_Level        0
Automation_Risk          0
Upskilling_Required      0
Salary_Before_AI         0
Salary_After_AI          0
Job_Status               0
Work_Hours_Per_Week      0
Remote_Work              0
Job_Satisfaction         0
Productivity_Change_%    0
dtype: int64

Total Missing Values: 0

# Check duplicate rows

Duplicate records are identified before data cleaning.

In [7]:
duplicates = df.duplicated().sum()

print('Duplicate Rows:', duplicates)

Duplicate Rows: 0

# Remove duplicate records

Duplicate records are removed to improve data quality.

In [8]:
df.drop_duplicates(inplace=True)

print('New Shape:', df.shape)

New Shape: (2000, 17)

# Check unique values

Unique values in categorical columns are examined to understand the available categories and detect inconsistent values.

In [9]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    print('\n' + '='*50)
    print('Column:', col)
    print('Unique Values:', df[col].nunique())
    print(df[col].value_counts())

==================================================
Column: Employee_ID
Unique Values: 2000
Employee_ID
E1984    1
E1983    1
E1982    1
E1981    1
E1980    1
        ..
E0005    1
E0004    1
E0003    1
E0002    1
E0001    1
Name: count, Length: 2000, dtype: int64

==================================================
Column: Gender
Unique Values: 3
Gender
Male      709
Female    652
Other     639
Name: count, dtype: int64

==================================================
Column: Education_Level
Unique Values: 4
Education_Level
Bachelor       529
Master         508
High School    497
PhD            466
Name: count, dtype: int64

==================================================
Column: Industry
Unique Values: 7
Industry
Finance          300
IT               298
Manufacturing    295
Education        293
Marketing        273
Retail           271
Healthcare       270
Name: count, dtype: int64

==================================================
Column: Job_Role
Unique Values: 21
Job_Role
Data Analyst          112
Quality Inspector     108
Store Manager         105
Investment Analyst    101
Teacher               100
Accountant            100
Auditor                99
Professor              98
Nurse                  96
SEO Specialist         95
Software Engineer      95
Machine Operator       95
Administrator          95
Digital Marketer       95
Supervisor             92
DevOps Engineer        91
Technician             89
Cashier                86
Doctor                 85
Content Creator        83
Sales Associate        80
Name: count, dtype: int64

==================================================
Column: AI_Adoption_Level
Unique Values: 3
AI_Adoption_Level
High      705
Medium    677
Low       618
Name: count, dtype: int64

==================================================
Column: Automation_Risk
Unique Values: 3
Automation_Risk
High      682
Medium    668
Low       650
Name: count, dtype: int64

==================================================
Column: Upskilling_Required
Unique Values: 2
Upskilling_Required
Yes    1026
No      974
Name: count, dtype: int64

==================================================
Column: Job_Status
Unique Values: 3
Job_Status
Unchanged    1093
Modified      801
Replaced      106
Name: count, dtype: int64

==================================================
Column: Remote_Work
Unique Values: 2
Remote_Work
No     1027
Yes     973
Name: count, dtype: int64

# Statistical summary

Descriptive statistics are generated for all numerical columns.

In [10]:
df.describe().T

                        count         mean           std       min        25%       50%          75%        max
Age                    2000.0     40.55800     10.786418     22.00     32.000     40.00      50.0000      59.00
Years_Experience       2000.0     16.66350     10.746675      0.00      8.000     16.00      26.0000      37.00
Salary_Before_AI       2000.0  73942.07250  26055.823793  30036.00  51665.500  74620.00   95418.2500  119976.00
Salary_After_AI        2000.0  78428.64250  29351.599013  24447.00  54086.750  76820.50  100730.2500  161745.00
Work_Hours_Per_Week    2000.0     44.85100      5.712540     35.00     40.000     45.00      50.0000      54.00
Job_Satisfaction       2000.0      6.02050      2.006263      3.00      4.000      6.00       8.0000       9.00
Productivity_Change_%  2000.0      9.78582     17.187882    -19.99     -5.355      9.85      24.5825      39.99

# Categorical summary

A summary of categorical columns is generated.

In [11]:
df.describe(include='object').T

                    count unique           top  freq
Employee_ID          2000   2000         E1984     1
Gender               2000      3          Male   709
Education_Level      2000      4      Bachelor   529
Industry             2000      7       Finance   300
Job_Role             2000     21  Data Analyst   112
AI_Adoption_Level    2000      3          High   705
Automation_Risk      2000      3          High   682
Upskilling_Required  2000      2           Yes  1026
Job_Status           2000      3     Unchanged  1093
Remote_Work          2000      2            No  1027

# Data cleaning

Extra spaces are removed from all categorical column

In [12]:
for col in categorical_cols:
    df[col] = df[col].str.strip()

print('Text columns cleaned successfully')

Text columns cleaned successfully

# Feature engineering

New analytical features are created to measure the impact of AI on employee salaries.

In [13]:
# Salary Difference
df['Salary_Difference'] = (
    df['Salary_After_AI'] -
    df['Salary_Before_AI']
)

# Salary Growth Percentage
df['Salary_Growth_%'] = (
    df['Salary_Difference'] /
    df['Salary_Before_AI']
) * 100

df[['Salary_Before_AI',
    'Salary_After_AI',
    'Salary_Difference',
    'Salary_Growth_%']].head()

   Salary_Before_AI  Salary_After_AI  Salary_Difference  Salary_Growth_%
0            106820            95455             -11365       -10.639393
1             74131            72013              -2118        -2.857104
2             35311            42290               6979        19.764379
3            114478           107820              -6658        -5.815965
4             33890            40945               7055        20.817350

# Create experience categories

Employees are grouped into experience categories for easier analysis.

In [14]:
def experience_category(exp):

    if exp <= 2:
        return 'Fresher'

    elif exp <= 5:
        return 'Junior'

    elif exp <= 10:
        return 'Mid-Level'

    else:
        return 'Senior'

df['Experience_Category'] = (
    df['Years_Experience']
    .apply(experience_category)
)

df[['Years_Experience',
    'Experience_Category']].head()

   Years_Experience Experience_Category
0                26              Senior
1                19              Senior
2                28              Senior
3                24              Senior
4                 0             Fresher

# Save cleaned dataset

The cleaned and transformed dataset is exported as a new CSV file for further analysis.

In [15]:
df.to_csv(
    'AI_Job_Impact_Cleaned.csv',
    index=False
)

print('Cleaned dataset saved successfully')

Cleaned dataset saved successfully

# Conclusion

The AI Job Impact dataset was successfully prepared for analysis. The dataset was inspected, cleaned, and enriched with new analytical features. The cleaned dataset is now ready for exploratory data analysis and visualization.